### ISSUE TITLE
It would be nice if we can start shapes from a width/height/radius.

### ISSUE THREAD

**Issue by mostafaimran** [poldz123/ShapeRipple#2]
Basically I was searching for this kinda ripple effects. In addition I was searching for a circle ripple with a given initial/minimum radius of the circle and number of ripple limited, as the ripple circle would initiate from a base radius and we can control the number of ripple.

If you add these functionalities, it would be a complete ripple tool.

Thanks a lot, CHEERS!

**Comment by poldz123** [comment]
This feature is currently in progress and will be release on 1.0v

It may take time to be release maybe during that time you can check the develop branch which will be updated.

**Comment by poldz123** [comment]
This should be added in the new release, cheers.
